<?php

if (!defined('ADMIN_TOKEN_KEY')) define('ADMIN_TOKEN_KEY', 'ADMIN_TOKEN');

if (!defined('DATABASE_HOST_KEY')) define('DATABASE_HOST_KEY', 'DATABASE_HOST');
if (!defined('DATABASE_NAME_KEY')) define('DATABASE_NAME_KEY', 'DATABASE_NAME');
if (!defined('DATABASE_USERNAME_KEY')) define('DATABASE_USERNAME_KEY', 'DATABASE_USERNAME');
if (!defined('DATABASE_PASSWORD_KEY')) define('DATABASE_PASSWORD_KEY', 'DATABASE_PASSWORD');
if (!defined('DATABASE_URL_KEY')) define('DATABASE_URL_KEY', 'DATABASE_URL');
if (!defined('DATABASE_TABLE_COLUMN_SEPARATOR')) define('DATABASE_TABLE_COLUMN_SEPARATOR', '____1299ej229jsd922dj92___');

